version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      version-updates:
        applies-to: version-updates
        patterns:
          - "*"
